---
- hosts: localhost  
  gather_facts: false
- name: initiate AWS instance
  roles:
    - ec2_launch

- name: install Apache in AWS instance(s)
  hosts: launched
  remote_user: ec2-user
  become: True
  gather_facts: true
  roles:
    - httpd
