---
- hosts: localhost  
  gather_facts: false
  tasks:
    - name: Install PIP Boto
      yum: name=python-pip update_cache=yes state=present
    - name: Install python-Boto
      pip: name=boto state=present
    - name: provision EC2 Instance
      ec2:
        key_name: "ChefWS"
        instance_type: "t2.micro"
        image: "ami-0b1e356e"
        count: 1
        group_id: "sg-ea78b881"
        region: "us-east-2"
        state: "present"
        wait: yes
        instance_tags:
            Name: WebServer
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
        ansible_user: ec2-user
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  remote_user: ec2-user
  become: True
  gather_facts: true
  roles:
    - httpd
